package com.unity3d.services.ads.adunit;

public enum AdUnitError {
	ADUNIT_NULL,
	ACTIVITY_ID,
	GENERIC,
	ORIENTATION,
	SCREENVISIBILITY,
	CORRUPTED_VIEWLIST,
	CORRUPTED_KEYEVENTLIST,
	SYSTEM_UI_VISIBILITY,
	UNKNOWN_VIEW,
	LAYOUT_NULL,
	MAX_MOTION_EVENT_COUNT_REACHED,
	API_LEVEL_ERROR,
	NO_DISPLAY_CUTOUT_AVAILABLE,
	DISPLAY_CUTOUT_METHOD_NOT_AVAILABLE,
	DISPLAY_CUTOUT_JSON_ERROR,
	DISPLAY_CUTOUT_INVOKE_FAILED
}