package com.unity3d.ads.device;

public enum DeviceError {
	APPLICATION_CONTEXT_NULL,
	APPLICATION_INFO_NOT_AVAILABLE,
	AUDIOMANAGER_NULL,
	INVALID_STORAGETYPE,
	COULDNT_GET_STORAGE_LOCATION,
	COULDNT_GET_GL_VERSION,
	JSON_ERROR,
	COULDNT_GET_DIGEST,
	COULDNT_GET_FINGERPRINT,
	COULDNT_GET_ADB_STATUS
}
