package com.unity3d.services.ar;

public enum AREvent {
	AR_PLANES_ADDED,
	AR_PLANES_REMOVED,
	AR_PLANES_UPDATED,
	AR_ANCHORS_UPDATED,
	AR_FRAME_UPDATED,
	AR_WINDOW_RESIZED,
	AR_ERROR,
	AR_SESSION_INTERRUPTED,
	AR_SESSION_INTERRUPTION_ENDED,
}
