# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Runs all of the instrumentation tests"
  lane :instrumentation_test do
    gradle(
      task: "connectedDebugAndroidTest",
      flags: "-w -Pandroid.testInstrumentationRunnerArguments.class=com.unity3d.ads.test.InstrumentationTestSuite"
    )
  end

  desc "Runs all of the instrumentation tests"
  lane :legacy_test do
    gradle(
      task: "connectedDebugAndroidTest",
      flags: "-w -Pandroid.testInstrumentationRunnerArguments.class=com.unity3d.ads.test.LegacyTestSuite"
    )
  end

  desc "Runs all of the integration tests"
  lane :integration_test do
    gradle(
      task: "connectedDebugAndroidTest",
      flags: "-w -Pandroid.testInstrumentationRunnerArguments.class=com.unity3d.ads.test.IntegrationTestSuite"
    )
  end

end
